#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'sudo'
cookbook 'nginx'
cookbook 'postgresql'
cookbook 'gitolite',
  :git => 'https://github.com/wschultz/cookbook-gitolite.git'
#cookbook 'ruby'
cookbook 'rbenv'
#  :git => 'git://github.com/fnichol/chef-rbenv.git', :ref => 'v0.7.2'
cookbook 'ruby_build'
